permissions:
  contents: write
name: Update PPV Playlist

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install chromium

      - name: Run script
        run: python script.py

      - name: Commit playlist
        run: |
          git config --global user.name "iptv-bot"
          git config --global user.email "bot@github.com"

          if [ -f ppv.m3u ]; then
            git add ppv.m3u
            git commit -m "update playlist" || echo "no changes"
            git push
          else
            echo "No playlist generated"
          fi
